travis:
  secure:
    BINSTAR_TOKEN: acBpMI0Mw/z/xKimzcv2N2LbZhyZWyoYRr/yRJHVM1BYwf9QeFohBXQPprfv8qCL8rybh8Jb8PG+5l+Lt2NVbCHwlQCh2uHJj9G56vA7ZWqjNK8tH4mRUN0XqJdxAi+qrhaQL0oQs7MnhYbM/zQrqp6irCN6wbwIn4DXJ1wiG5j6NCqpx3FD1vfdtxUNDk25YwsC4dsfzwZGiOJ9df467eSmKUnUM8w70McSzMi9c675L4a8Qho1Ztxtuw4K1bfcg9zUBLXn4/n34oo6g8uN/2afhCtrBC64yn9Y0vZu5QHxuKnmj8+Xf9+xK+INbsMozKBFlmFmst1Ko6m1ugEKTaxOHtAkJRMg/J5lWM3oZajmma6WyCGujzW8DFo1zwXYNxXhcqvBdkSgJWbKeXStS0qHxqWgZygyi9257ZcrY57l7XR5x/QHStSFFDgkzfmXlezXD88sMD1Id9EhIk16cdx4SzX2g8tOgcz8yy9vMuwyxeq4iHib5C3jnz9dYz1QdjMZXwZMnGPU8YoZW1RqXqt0cPAKXC4l29Uh0JJNLa61Fj8aDECZbAW0vUCNKLc+U6QWVUgeJXlLsl492CZ3XDfacKIcp3gv0AN6O+c84NEnpSRdt29VamvbrcRhUjUC0mf73dQtegTgo5T+lANcVYxvA9A8fm25q94ctjZBH4A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
